<script>
  import background from '$lib/assets/background01.jpg';
  import profile from '$lib/assets/images/profile00.png';
  import backgroundImageNDBC from '$lib/assets/images/button-background-ndbc-api.png';
  import backgroundImageAq from '$lib/assets/images/button-background-aq.png';
  import backgroundImageEgh from '$lib/assets/images/button-background-explore-github.png';


  export let projects = [
		{
			shortName: "Explore GitHub",
			url: "https://discover-open-source.fly.dev/",
			longDescription: "Visualizes the relationships between the top contributors for a given repository with other projects they contribute to.<br>Double-click on any of these connected repositories to continue exploring.",
      backgroundImage: backgroundImageEgh,
		},
    {
			shortName: "Operational Air Quality Forecasting",
			url: "https://air-quality-forecast.fly.dev/",
			longDescription: "A real-time forecasting system for air quality in the United States.<br>The system visualizes forecasts generated by an operational graph neural network model.<br>Forecasting skill metrics for the previous 24 hours are also available; skill scores vary but the error is generally 50% lower than the EPA's AQI forecast.",
      backgroundImage: backgroundImageAq,
		},
		{
			shortName: "National Data Buoy Center API",
			url: "https://github.com/cdjellen/ndbc-api",
			longDescription: "This Python package provides streamlined, efficient access to NDBC's global buoy data, accelerating data acquisition and preprocessing.<br>It empowers researchers with the tools for advanced oceanographic and meteorological analysis.",
      backgroundImage: backgroundImageNDBC,
		},
	];
	let hoveredProject = null;

  function handleMouseEnter(project) {
    hoveredProject = project;
  }
  function handleMouseLeave(){
    hoveredProject = null;
  }
  function formatDescription(description) {
    return description.replace(/\n/g, "<br>");
  }
</script>

<div
  class="banner" 
  style="background-image: url('{background}');"
  id="banner"
>
  <div class="content-wrapper">
    <img 
      class="profile-image rounded-full border-4 border-solid border-gray-900"
      src="{profile}" 
      alt="profile"
    >

    <div class="text-container">
      <h1 class="name text-outline-lg font-bold">Christopher Jellen</h1>
      <h5 class="title text-outline">Machine Learning Research | Automation Engineering</h5>
	  </div>
  </div>
  <div class="button-container">
		{#each projects as project}
			<a
        href={project.url}
        class="project-button"
        style="background-image: url('{project.backgroundImage}');"
        on:mouseenter={() => handleMouseEnter(project)}
        on:mouseleave={handleMouseLeave}
        rel="noopener noreferrer"
        target="_blank"
        >
				<span class="button-text">{@html project.shortName}</span>
        {#if hoveredProject === project}
          <span class="tooltip">{@html formatDescription(project.longDescription)}</span>
        {/if}
			</a>
		{/each}
	</div>
</div>


<style>
.banner {
  min-height: 100vh; 
  width: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background-size: cover;
  background-position: center;
  background-blend-mode: overlay;
  background-color: rgba(0, 0, 0, 0.5);
  gap: 5rem;
}

.content-wrapper {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  gap: 1rem;
}

.profile-image {
  width: 200px;
  height: 200px;
  object-fit: cover;
}

.text-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.5rem;
}

.name {
  font-size: 2rem;
}

.title {
  font-size: 1rem;
}

.button-container {
  display: flex;
  gap: 10px; /* Space between buttons */
  margin-top: 20px; /* Space between text and buttons */
}
.button-text {
  position: absolute; /* Absolute positioning within the button */
  bottom: 10px;       /* Position at the bottom */
  left: 50%;
  transform: translateX(-50%); /* Center horizontally */
  width: 100%;       /* Take up full width of button */
  text-align: center; /* Center text horizontally */
  font-size: 1.4rem;
  text-shadow:
    -1px -1px 2px rgba(0, 0, 0, 0.8),  /* Small offset, slight blur, slightly transparent */
    1px -1px 2px rgba(0, 0, 0, 0.8),
    -1px  1px 2px rgba(0, 0, 0, 0.8),
    1px  1px 2px rgba(0, 0, 0, 0.8),
    -2px -2px 4px rgba(0, 0, 0, 0.6),  /* Larger offset, more blur, more transparent */
    2px -2px 4px rgba(0, 0, 0, 0.6),
    -2px  2px 4px rgba(0, 0, 0, 0.6),
    2px  2px 4px rgba(0, 0, 0, 0.6);
  z-index: 2;        /* Ensure text is above the background image */
}
.project-button {
  padding: 20px 25px;
  color: white;
  border: none;
  border-radius: 8px; /* Rounded corners */
  cursor: pointer;
  text-decoration: none; /* Remove underline from links */
  text-align: center;
  font-size: 1rem;
  position: relative; /* For tooltip positioning */
  display: inline-block; /* For consistent sizing */
  background-size: cover;
  background-position: center;
  min-width: 360px;
  min-height: 240px;
  transition: background-color 0.2s ease;
}
.project-button:hover {
  filter: brightness(0.9);
}

.tooltip {
  display: none; /* Hidden by default */
  position: absolute;
  bottom: calc(100% + 5px);
  left: 50%;
  transform: translateX(-50%);
  background-color: rgba(0, 0, 0, 0.8);
  color: white;
  padding: 5px 10px;
  border-radius: 5px;
  z-index: 10;
  pointer-events: none;
  text-align: center; /* Center the text within */
  width: max-content;
  min-width: 5rem; /* Add a minimum width */
  max-width: 80vw;  /* Prevent overly wide tooltips */
  word-wrap: break-word; /* Allow long words to break */
  white-space: normal;
  opacity: 0;
  transition: opacity 0.2s ease;
}
.project-button:hover .tooltip{
  display: block;
  opacity: 1;
}
.project-button:focus .tooltip {
  display: block;
  opacity: 1;
}

.text-outline {
  text-shadow:
    -1px -1px 0 #000,
    1px -1px 0 #000,
    -1px  1px 0 #000,
    1px  1px 0 #000;
}
.text-outline-lg {
  text-shadow:
    -2px -2px 0 #000,
    2px -2px 0 #000,
    -2px  2px 0 #000,
    2px  2px 0 #000;
}

/* Media Queries for Different Screen Sizes */
@media (min-width: 640px) { 
  .content-wrapper {
    flex-direction: row;
    gap: 2rem;
  }

  .profile-image {
    width: 300px; 
    height: 300px;
  }

  .name {
    font-size: 3rem;
  }
}
</style>
